POST http://localhost:3000/authentication/sign-up
Content-Type: application/json

{
	"email": "user1@nestjs.com",
	"password": "Password!123"
}

###
POST http://localhost:3000/authentication/sign-in
Content-Type: application/json
Authorization: Bearer

{
	"email": "user1@nestjs.com",
	"password": "Password!123"
}

> {%
  client.global.set("auth_token", response.body.accessToken);
  client.global.set("refresh_token", response.body.refreshToken);
%}
###
POST http://localhost:3000/authentication/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
  client.global.set("auth_token", response.body.accessToken);
  client.global.set("refresh_token", response.body.refreshToken);
%}
###
GET http://localhost:3000/coffees
Content-Type: application/json
Authorization: Bearer {{auth_token}}

